/* nocode_dispatch.h — device nocode dispatch ABI (C/C++ interop).
 * Generated by scripts/classes/class_logic_transposer.py; the ABI is stable, the table is per-build.
 */
#ifndef NOCODE_DISPATCH_H
#define NOCODE_DISPATCH_H
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
#ifndef NC_MAX_ARGS
#define NC_MAX_ARGS   8
#endif
#ifndef NC_MAX_DIGITS
#define NC_MAX_DIGITS 32
#endif
/* Shared execution context: prompt args (mirror host args[0]/arg0...), evaluate_ops operands, and
 * the captured result for inter-function data flow. */
typedef struct NcCtx {
    const char* args[NC_MAX_ARGS];
    int         argc;
    long        a, b;
    long        digits[NC_MAX_DIGITS];
    int         ndigits;
    long        result;
    int         has_result;
} NcCtx;
typedef long (*NcFn)(NcCtx* ctx);                 /* a dispatched compiled function */
typedef struct NcEntry { const char* grammar; const char* token; NcFn fn; } NcEntry;
extern const NcEntry NC_DISPATCH[];
extern const int     NC_DISPATCH_COUNT;
NcFn nc_resolve(const char* grammar, const char* token);   /* (grammar,token) -> fn | NULL */
#ifdef __cplusplus
}
#endif
#endif /* NOCODE_DISPATCH_H */
