/**
 * llm_fsbl.c
 *
 * FSBL-mode inference: CM55 does embedding lookup (int8), ATON NPU runs
 * the transformer body.  No dependency on app_x-cube-ai or bsp_ai.
 *
 * Memory:
 *   s_net_ctx    → .bss  AXISRAM2          (ATON context, ~4KB)
 *   Activations  → managed by ATON runtime  (AXISRAM3-6, no user buffer)
 *   Weights      → NOR flash 0x70000000     (1.31 MB, memory-mapped)
 */

#include "llm_fsbl.h"
#include "llm_tokenizer.h"
#include "llm_embed.h"   /* embed table int8[374][256], EMBED_ZP, MASK_ONE/ZERO */

#include <string.h>
#include "stai_network.h"  /* NPU STAI API generated by atonn */
#include "stai.h"

/* ── ATON network context in AXISRAM2 ───────────────────────────────────── */

STAI_NETWORK_CONTEXT_DECLARE(s_net_ctx, STAI_NETWORK_CONTEXT_SIZE);

/* ── Small pointer arrays ───────────────────────────────────────────────── */

static stai_ptr s_inp[STAI_NETWORK_IN_NUM];
static stai_ptr s_out[STAI_NETWORK_OUT_NUM];
static int      s_initialised = 0;

/* Debug variables in AXISRAM2 .bss */
volatile uint32_t s_dbg_buf0_addr;
volatile int32_t  s_dbg_tok0;
volatile int32_t  s_dbg_tok1;
volatile int32_t  s_dbg_tok2;
volatile int32_t  s_dbg_tok3;
volatile uint32_t s_dbg_stai_err;
volatile int8_t   s_dbg_logit0;
volatile int8_t   s_dbg_logit_max;
volatile int32_t  s_dbg_argmax;

/* ── Helpers ────────────────────────────────────────────────────────────── */

static int argmax_i8(const int8_t *arr, int n)
{
    int best = 0;
    for (int i = 1; i < n; i++)
        if (arr[i] > arr[best]) best = i;
    return best;
}

/* ── Public API ─────────────────────────────────────────────────────────── */

int LLM_FSBL_Init(void)
{
    stai_return_code err;
    stai_size n;

    /* ATON path: stai_network_init handles everything (weights at 0x70000000) */
    err = stai_network_init(s_net_ctx);
    if (err != STAI_SUCCESS) return -(int)err;

    /* NPU manages activations in AXISRAM3-6 — no user activation buffer */

    /* States = 0 for this model */

    /* Get preallocated input/output buffers from ATON runtime */
    err = stai_network_get_inputs(s_net_ctx, s_inp, &n);
    if (err != STAI_SUCCESS) return -(int)err;

    err = stai_network_get_outputs(s_net_ctx, s_out, &n);
    if (err != STAI_SUCCESS) return -(int)err;

    /* Canary: prove s_inp[0] is accessible */
    volatile int8_t *p = (volatile int8_t *)s_inp[0];
    p[0] = 42;
    s_dbg_tok0 = (int32_t)p[0];
    p[0] = 0;

    s_initialised = 1;
    return 0;
}

void LLM_FSBL_Deinit(void)
{
    if (s_initialised) {
        stai_network_deinit(s_net_ctx);
        s_initialised = 0;
    }
}

int LLM_FSBL_RunOnce(const int32_t *input_ids, const int32_t *attn_mask,
                     int seq_len, int32_t *next_token_id)
{
    if (!s_initialised) return -1;

    /*
     * Input 0: int8[1,32,256] embedding — CHANNEL_LAST = row[pos][dim]
     * Quantization: scale=LLM_EMBED_SCALE, zero_point=LLM_EMBED_ZP
     *   The embed table is already quantized with the same parameters,
     *   so copying int8 rows directly is correct.
     *
     * Modelfile template: "<|endoftext|>{{ .Prompt }}"
     *   → BOS (token 0) must be at position 0.
     */
    int8_t *emb_buf  = (int8_t *)s_inp[0];
    int8_t *mask_buf = (int8_t *)s_inp[1];
    int cpy = (seq_len < LLM_SEQ_LEN - 1) ? seq_len : LLM_SEQ_LEN - 1;

    /* BOS at slot 0 */
    memcpy(emb_buf, llm_embed_table[LLM_EOS_TOKEN], LLM_HIDDEN_SIZE);
    mask_buf[0] = LLM_MASK_ONE;

    /* Real tokens at slots 1..cpy */
    for (int i = 0; i < cpy; i++) {
        int tok = input_ids[i];
        if (tok < 0 || tok >= LLM_VOCAB_SIZE) tok = 0;
        memcpy(emb_buf + (i + 1) * LLM_HIDDEN_SIZE,
               llm_embed_table[tok], LLM_HIDDEN_SIZE);
        mask_buf[i + 1] = attn_mask[i] ? LLM_MASK_ONE : LLM_MASK_ZERO;
    }

    /* Zero-pad slots cpy+1..31 (mask = padding → MASK_ZERO) */
    int pad_start = cpy + 1;
    int pad_count = LLM_SEQ_LEN - pad_start;
    if (pad_count > 0) {
        memset(emb_buf  + pad_start * LLM_HIDDEN_SIZE, LLM_EMBED_ZP, pad_count * LLM_HIDDEN_SIZE);
        memset(mask_buf + pad_start, LLM_MASK_ZERO, pad_count);
    }

    /* Capture debug snapshot */
    s_dbg_buf0_addr = (uint32_t)(uintptr_t)emb_buf;
    s_dbg_tok0 = (int32_t)((int8_t)emb_buf[0]);  /* first dim of BOS embed */
    s_dbg_tok1 = (int32_t)((int8_t)emb_buf[1]);
    s_dbg_tok2 = (int32_t)mask_buf[0];
    s_dbg_tok3 = (int32_t)mask_buf[1];

    /* Run ATON NPU */
    stai_return_code err = stai_network_run(s_net_ctx, STAI_MODE_SYNC);
    s_dbg_stai_err = (uint32_t)err;
    if (err != STAI_SUCCESS) return -(int)err;

    /* Argmax at last real token position (shifted +1 for BOS at slot 0) */
    const int8_t *logits = (const int8_t *)s_out[0];
    int last = (cpy < LLM_SEQ_LEN - 1) ? cpy : LLM_SEQ_LEN - 1;
    const int8_t *row = logits + last * LLM_VOCAB_SIZE;

    s_dbg_logit0 = row[0];
    int8_t mx = row[0];
    for (int i = 1; i < LLM_VOCAB_SIZE; i++) if (row[i] > mx) mx = row[i];
    s_dbg_logit_max = mx;
    s_dbg_argmax = (int32_t)argmax_i8(row, LLM_VOCAB_SIZE);
    *next_token_id = s_dbg_argmax;

    return 0;
}

int LLM_FSBL_Generate(const char *prompt, char *out_buf, int out_max, int max_new_tokens)
{
    int32_t ids[LLM_SEQ_LEN]  = {0};
    int32_t mask[LLM_SEQ_LEN] = {0};
    int out_pos    = 0;
    int new_tokens = 0;

    int n = LLM_Tokenize(prompt, ids, mask, LLM_SEQ_LEN);
    if (n <= 0) return 0;

    while (new_tokens < max_new_tokens) {
        int32_t next_tok;
        if (LLM_FSBL_RunOnce(ids, mask, n, &next_tok) != 0) return -1;

        if (next_tok == LLM_EOS_TOKEN) break;

        const char *tok_str = LLM_TokenStr(next_tok);
        int tok_len = (int)strlen(tok_str);
        if (out_pos + tok_len < out_max - 1) {
            memcpy(out_buf + out_pos, tok_str, tok_len);
            out_pos += tok_len;
        }
        new_tokens++;

        /* Slide context window */
        if (n < LLM_SEQ_LEN) {
            ids[n]  = next_tok;
            mask[n] = 1;
            n++;
        } else {
            memmove(ids,  ids  + 1, (LLM_SEQ_LEN - 1) * sizeof(int32_t));
            memmove(mask, mask + 1, (LLM_SEQ_LEN - 1) * sizeof(int32_t));
            ids[LLM_SEQ_LEN - 1]  = next_tok;
            mask[LLM_SEQ_LEN - 1] = 1;
        }
    }

    out_buf[out_pos] = '\0';
    return new_tokens;
}
