"""classes/class_tools_grammar.py

Grammar and vocabulary file generators from external source formats.

Inheritance tree:
    BaseGrammarConverter
        ├── MermaidGrammarConverter   (.mmd / .txt Mermaid flowcharts)
        ├── MarkdownGrammarConverter  (.md files)
        ├── PDFGrammarConverter       (.pdf files via pypdf)
        └── WebGrammarConverter       (http/https URLs via urllib + html.parser)

Each converter populates:
    self._rules   {rule_name: [child_name, ...]}   non-terminal rules
    self._tokens  {token_name: command_string}      terminal command tokens

Output (via .generate()):
    training/train_<grammar>_commands.json   — command vocabulary JSON
    grammars/playbook_<grammar>.txt          — BNF grammar file
"""

import os, re, json
from collections import OrderedDict


# ─────────────────────────────────────────────────────────────────────────────
# Base
# ─────────────────────────────────────────────────────────────────────────────

class BaseGrammarConverter:
    """Shared logic for all grammar source converters.

    Subclasses implement parse() to populate self._rules and self._tokens.

    Internal state:
        _rules   OrderedDict {rule_name: [child_name, ...]}
                 Non-terminal rules only — children may be other rules or token names.
        _tokens  dict {token_name: command_string}
                 Leaf command tokens (terminal nodes in the grammar tree).

    The grammar name is derived from the source filename when not supplied
    explicitly.  Subclasses may override self.grammar_name inside parse() if
    the source document carries a better name (e.g. a Markdown H1 heading).
    """

    def __init__(self, source, grammar_name=None, exec_mode="shell"):
        self.source      = source
        self.exec_mode   = exec_mode
        self._rules      = OrderedDict()
        self._tokens     = OrderedDict()
        self._name_explicit = bool(grammar_name)

        if grammar_name:
            self.grammar_name = self._sanitize(grammar_name)
        else:
            stem = os.path.splitext(os.path.basename(str(source).rstrip("/")))[0]
            self.grammar_name = self._sanitize(stem) or "grammar"

    # ── name utilities ──────────────────────────────────────────────────────

    @staticmethod
    def _sanitize(text):
        """Convert arbitrary text to a valid snake_case grammar token name."""
        text = re.sub(r'[^a-zA-Z0-9 _\-]', '', str(text))
        text = re.sub(r'[ \-]+', '_', text.strip())
        return text.lower().strip('_') or "item"

    def _unique_name(self, name, existing):
        """Return name, appending _2 / _3 ... if already taken."""
        if name not in existing:
            return name
        i = 2
        while (name + "_" + str(i)) in existing:
            i += 1
        return name + "_" + str(i)

    # ── subclass contract ───────────────────────────────────────────────────

    def parse(self):
        """Parse self.source and populate self._rules / self._tokens."""
        raise NotImplementedError

    # ── output serialisation ────────────────────────────────────────────────

    def to_vocabulary_dict(self):
        """Return the command vocabulary as a dict (ready for json.dump)."""
        d = OrderedDict()
        d["_type"]    = "command_vocabulary"
        d["_grammar"] = self.grammar_name
        if self.exec_mode != "shell":
            d["_exec"] = self.exec_mode
        d.update(self._tokens)
        return d

    def to_grammar_text(self):
        """Return a BNF grammar string compatible with ModelGrammar.load_file()."""
        lines = [
            "# Generated by model_tools_grammar.py",
            "# Grammar : " + self.grammar_name,
            "# Source  : " + str(self.source),
            "# Exec    : " + self.exec_mode,
            "",
        ]
        # Non-terminal rules
        for rule, children in self._rules.items():
            parts = []
            for c in children:
                if c in self._rules:
                    parts.append("<" + c + ">")
                else:
                    parts.append('"' + c + '"')
            lines.append("<" + rule + ">  ::=  " + " ".join(parts))
        # Terminal self-reference rules for every token not already in _rules
        for tok in self._tokens:
            if tok not in self._rules:
                lines.append("<" + tok + ">  ::=  " + '"' + tok + '"')
        return "\n".join(lines) + "\n"

    def generate(self, output_dir="."):
        """Write vocabulary JSON and BNF grammar file.

        Returns (json_path, bnf_path).
        """
        os.makedirs(output_dir, exist_ok=True)
        json_path = os.path.join(output_dir,
                                 "train_" + self.grammar_name + "_commands.json")
        bnf_path  = os.path.join(output_dir,
                                 "playbook_" + self.grammar_name + ".txt")
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump(self.to_vocabulary_dict(), fh, indent=2, ensure_ascii=False)
        with open(bnf_path, "w", encoding="utf-8") as fh:
            fh.write(self.to_grammar_text())
        return json_path, bnf_path

    def summary(self):
        """Return a human-readable summary string of the parsed structure."""
        lines = [
            "Grammar : " + self.grammar_name + "  [exec=" + self.exec_mode + "]",
            "Rules   : " + str(len(self._rules)),
            "Tokens  : " + str(len(self._tokens)),
        ]
        for i, (rule, children) in enumerate(self._rules.items()):
            if i >= 6:
                lines.append("  ... (" + str(len(self._rules) - 6) + " more)")
                break
            lines.append("  <" + rule + ">  ::=  " + " ".join(children))
        return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Mermaid flowchart  (.mmd or any text file containing a Mermaid diagram)
# ─────────────────────────────────────────────────────────────────────────────

class MermaidGrammarConverter(BaseGrammarConverter):
    """Convert a Mermaid flowchart diagram to grammar + vocabulary files.

    Supported Mermaid syntax:
        flowchart TD / graph TD / graph LR  (direction keyword is ignored)
        Nodes : A[Label]  A(Label)  A{Label}  A((Label))  A>Label]
        Edges : A --> B   A -->|label| B   A --- B   A -.-> B   A ==> B

    Two ways to attach commands to leaf tokens:

    1. Comment annotation  (recommended — diagram stays valid Mermaid):
            %% cmd: ping_sweep = nmap -sn 192.168.1.0/24
            %% cmd: save_results = nmap -oA /tmp/out 192.168.1.0/24

    2. Label-as-command  (when the node ID is already snake_case):
            discovery --> ping_sweep["nmap -sn 192.168.1.0/24"]
            discovery --> arp_scan["arp-scan --localnet"]
       The ID becomes the token name; the bracket text becomes the command.
       Detection: node ID matches ^[a-z][a-z0-9_]+$ and label ≠ sanitized ID.

    Conversion rules:
        - Nodes with outgoing edges become grammar rules.
        - Leaf nodes (no outgoing edges) become command tokens.
        - %% cmd: annotations always win over label-derived commands.
        - The overall grammar root is injected when there are multiple entry nodes.
    """

    # Matches node definitions:  ID[label]  ID(label)  ID{label}  ID((label))
    _NODE_RE = re.compile(
        r'([A-Za-z0-9_]+)\s*'
        r'(?:\[\[([^\]]*)\]\]'      # [[double square]]
        r'|\[([^\]]*)\]'            # [square]
        r'|\(\(([^)]*)\)\)'         # ((circle))
        r'|\(([^)]*)\)'             # (round)
        r'|\{([^}]*)\}'             # {diamond}
        r'|>([^\]]*)\])'            # >asymmetric]
    )

    # Matches directed edges between two node IDs
    _EDGE_RE = re.compile(
        r'([A-Za-z0-9_]+)\s*'
        r'(?:-->|---|==>|-.->|--x|--o|==)'
        r'(?:\|[^|]*\|)?\s*'
        r'([A-Za-z0-9_]+)'
    )

    # %% cmd: token_name = command string
    _CMD_RE = re.compile(r'^%%\s*cmd:\s*(\w+)\s*=\s*(.+)', re.IGNORECASE)

    # Node ID that is already a valid snake_case identifier (use as token name directly)
    _SNAKE_ID = re.compile(r'^[a-z][a-z0-9_]+$')

    def parse(self):
        with open(self.source, "r", encoding="utf-8") as fh:
            text = fh.read()

        node_labels  = {}            # id → display label (or command if label-as-cmd)
        node_is_cmd  = set()         # ids whose label is a command string
        cmd_overrides = {}           # token_name → command  (from %% cmd: lines)
        children_of  = OrderedDict() # id → [child_id, ...]
        in_degree    = {}            # id → count of incoming edges

        for line in text.splitlines():
            stripped = line.strip()
            if not stripped:
                continue

            # ── %% cmd: annotation ─────────────────────────────────────────
            m_cmd = self._CMD_RE.match(stripped)
            if m_cmd:
                cmd_overrides[m_cmd.group(1).strip()] = m_cmd.group(2).strip()
                continue

            # Skip other comments and diagram-type keywords
            if stripped.startswith("%%"):
                continue
            if re.match(r'^(?:flowchart|graph|sequenceDiagram|classDiagram)', stripped, re.I):
                continue

            # ── node label collection ──────────────────────────────────────
            for m in self._NODE_RE.finditer(line):
                nid   = m.group(1)
                label = next((g for g in m.groups()[1:] if g is not None), nid)
                label = label.strip()
                if nid not in node_labels and label:
                    node_labels[nid] = label
                    # Label-as-command: ID is snake_case and label differs from it
                    if (self._SNAKE_ID.match(nid)
                            and label != nid
                            and label != self._sanitize(label)):
                        node_is_cmd.add(nid)

            # ── edge collection ────────────────────────────────────────────
            for m in self._EDGE_RE.finditer(line):
                src, dst = m.group(1), m.group(2)
                children_of.setdefault(src, [])
                if dst not in children_of[src]:
                    children_of[src].append(dst)
                in_degree[dst] = in_degree.get(dst, 0) + 1

        # Fill in missing labels
        all_ids = set(children_of) | {d for kids in children_of.values() for d in kids}
        for nid in all_ids:
            node_labels.setdefault(nid, nid)

        # Roots: nodes with outgoing edges but no incoming edges
        roots = [n for n in children_of if in_degree.get(n, 0) == 0]
        if not roots and children_of:
            roots = [next(iter(children_of))]

        def token_name(nid):
            """Return the grammar token name for a node."""
            if nid in node_is_cmd:
                # Label is a command — use the ID itself as the name
                return self._sanitize(nid)
            return self._sanitize(node_labels.get(nid, nid)) or self._sanitize(nid)

        def token_cmd(nid):
            """Return the command string for a leaf node (empty string if unknown)."""
            name = token_name(nid)
            # %% cmd: annotation takes priority
            if name in cmd_overrides:
                return cmd_overrides[name]
            # Also check raw node ID in cmd_overrides
            if nid in cmd_overrides:
                return cmd_overrides[nid]
            # Label-as-command
            if nid in node_is_cmd:
                return node_labels.get(nid, "")
            return ""

        visited = set()

        def build(nid):
            if nid in visited:
                return
            visited.add(nid)
            name = token_name(nid)
            kids = children_of.get(nid, [])
            if kids:
                child_names = [token_name(k) for k in kids]
                self._rules[name] = child_names
                for k in kids:
                    build(k)
            else:
                self._tokens[name] = token_cmd(nid)

        if len(roots) == 1:
            root_name = token_name(roots[0])
            if root_name != self.grammar_name:
                self._rules[self.grammar_name] = [root_name]
            build(roots[0])
        else:
            root_names = [token_name(r) for r in roots]
            self._rules[self.grammar_name] = root_names
            for r in roots:
                build(r)


# ─────────────────────────────────────────────────────────────────────────────
# Markdown  (.md / .markdown)
# ─────────────────────────────────────────────────────────────────────────────

class MarkdownGrammarConverter(BaseGrammarConverter):
    """Convert a Markdown file to grammar + vocabulary files.

    Document structure mapping:
        H1  →  grammar name (overrides filename-derived name unless --grammar given)
        H2  →  top-level rule group  (child of grammar root)
        H3  →  sub-rule or token group  (child of current H2)
        Bullet (-/*)  →  token;  inline code or 'name: command' syntax → command value
        Fenced code block (```) →  command for the immediately preceding heading/bullet

    Example input:
        # pyhealthcheck
        ## System Status
        ### Check Kernel
        ```bash
        uname -r
        ```
        ### Check Uptime
        - uptime: `uptime -p`

        ## Network
        - check_ports: `ss -tuln`
    """

    def parse(self):
        with open(self.source, "r", encoding="utf-8") as fh:
            lines = fh.read().splitlines()

        # Section containers: h2_name → [child names in order]
        h2_children  = OrderedDict()
        h3_children  = OrderedDict()  # h3_name → [token names]

        current_h2   = None
        current_h3   = None
        in_code      = False
        code_buf     = []
        code_target  = None   # token / heading name the code block belongs to

        for line in lines:
            # ── fenced code block ──────────────────────────────────────────
            if re.match(r'^\s*```', line):
                if not in_code:
                    in_code     = True
                    code_buf    = []
                    code_target = current_h3 or current_h2
                else:
                    in_code = False
                    if code_target and code_buf:
                        tok = self._sanitize(code_target)
                        # strip language tag from first line if present
                        raw = code_buf[0].strip()
                        body = "\n".join(
                            code_buf[1:] if re.match(r'^[a-z]+$', raw) else code_buf
                        ).strip()
                        self._tokens[tok] = body
                    code_buf    = []
                    code_target = None
                continue

            if in_code:
                code_buf.append(line)
                continue

            # ── headings ───────────────────────────────────────────────────
            h1 = re.match(r'^# ([^#].+)', line)
            if h1:
                if not self._name_explicit:
                    self.grammar_name = self._sanitize(h1.group(1))
                continue

            h2 = re.match(r'^## ([^#].+)', line)
            if h2:
                current_h2  = h2.group(1).strip()
                current_h3  = None
                h2_key      = self._sanitize(current_h2)
                h2_children.setdefault(h2_key, [])
                code_target = current_h2
                continue

            h3 = re.match(r'^### ([^#].+)', line)
            if h3:
                current_h3  = h3.group(1).strip()
                h3_key      = self._sanitize(current_h3)
                h3_children.setdefault(h3_key, [])
                if current_h2:
                    h2k = self._sanitize(current_h2)
                    if h3_key not in h2_children.get(h2k, []):
                        h2_children.setdefault(h2k, []).append(h3_key)
                code_target = current_h3
                continue

            # ── bullet items  - name: command  or  - name  ─────────────────
            bullet = re.match(r'^\s*[-*]\s+(.+)', line)
            if bullet:
                item = bullet.group(1).strip()
                if ':' in item:
                    tok_label, _, cmd = item.partition(':')
                    tok  = self._sanitize(tok_label.strip())
                    cmd  = cmd.strip().strip('`')
                else:
                    tok  = self._sanitize(item.strip('`').strip())
                    cmd  = ""
                self._tokens.setdefault(tok, cmd)
                if cmd:
                    self._tokens[tok] = cmd

                # Add to the innermost open container
                parent = self._sanitize(current_h3) if current_h3 else (
                         self._sanitize(current_h2) if current_h2 else None)
                if parent:
                    bucket = h3_children if current_h3 else h2_children
                    bucket.setdefault(parent, [])
                    if tok not in bucket[parent]:
                        bucket[parent].append(tok)
                continue

        # ── assemble rules ─────────────────────────────────────────────────
        if h2_children:
            self._rules[self.grammar_name] = list(h2_children.keys())
            for h2k, children in h2_children.items():
                if children:
                    self._rules[h2k] = children
                    for c in children:
                        if c in h3_children:
                            self._rules[c] = h3_children[c]
                        else:
                            self._tokens.setdefault(c, "")
        elif self._tokens:
            self._rules[self.grammar_name] = list(self._tokens.keys())


# ─────────────────────────────────────────────────────────────────────────────
# Plain text specification documents
# ─────────────────────────────────────────────────────────────────────────────

class TextGrammarConverter(BaseGrammarConverter):
    """Convert a plain-text specification document to grammar + vocabulary files.

    Works with any text file that uses common doc conventions — no special
    markup required. Three levels of hierarchy are recognised:

    Section headings (become grammar rules):
        1. TITLE           — numbered section  (top-level)
        1.1  Sub-title     — numbered sub-section
        A. TITLE           — lettered section
        TITLE              — ALL-CAPS line or underline (=== / ---)

    Procedure steps (become command tokens):
        Step 1: text       — numbered step ("Step N:", "N.")
        • / - / * text     — bullet item
        → / > text         — arrow-prefixed step
        name: command      — explicit name:value pair (colon separator)

    Command extraction heuristic:
        A step line is split on the first ': ' or ':\t'.
        Left side → token name (sanitized).
        Right side → command value.
        If the value looks like a shell command (contains / - | > or spaces
        around a keyword like nmap, ping, curl, etc.) it is kept as-is.
        Otherwise the full line text is the command.

    For dense or loosely-structured specs, use --ai-model instead —
    the AI path gives much better results when structure is implicit.
    """

    # numbered section: "1.", "1.1", "1.1.", "1.1.2", "A.", "A.1" + title
    # requires at least one dot (so bare "1 Title" is not a section)
    _SEC_RE  = re.compile(r'^(\d+(?:\.\d+)+\.?|\d+\.|[A-Z](?:\.\d+)*\.)\s+(\S.+)')
    # ALL-CAPS heading (≥4 chars, may have trailing colon)
    _CAPS_RE = re.compile(r'^([A-Z][A-Z0-9 _/-]{3,}):?\s*$')
    # underline markers (===, ---, ~~~)
    _UL_RE   = re.compile(r'^[=\-~]{3,}\s*$')
    # bullet / arrow prefix (NOT "Step N:" — handled separately)
    _BULLET_RE = re.compile(r'^\s*[•\*→>]\s+(.+)|^\s*-\s{2,}(.+)')
    # "Step N: ..." or just "N. ..." at start of line
    _STEP_RE   = re.compile(r'^\s*(?:step\s+)?(\d+)[.:]\s+(.+)', re.IGNORECASE)
    # em-dash separators used to split "name — command" in step text
    _EMDASH_RE = re.compile(r'\s+[—–-]{1,3}\s+')

    # valid name: short phrase, no colons/slashes/IPs/dots
    _NAME_OK = re.compile(r'^[A-Za-z][A-Za-z0-9 _-]{0,39}$')

    def _split_name_cmd(self, text):
        """Split 'name — command' or 'name: command' into (name, cmd).
        Returns (None, text) if no clean split is found.
        Name must be a short clean phrase (no colons, slashes, IP addresses).
        """
        m = self._EMDASH_RE.search(text)
        if m:
            left = text[:m.start()].strip()
            right = text[m.end():].strip()
            # name must be a clean short phrase, command must be non-trivial
            if self._NAME_OK.match(left) and len(right) > 3:
                return left, right
        if ': ' in text:
            left, _, right = text.partition(': ')
            if (self._NAME_OK.match(left.strip())
                    and len(left.split()) <= 3
                    and len(right.strip()) > 3):
                return left.strip(), right.strip()
        return None, text

    def parse(self):
        with open(self.source, "r", encoding="utf-8") as fh:
            raw_lines = fh.read().splitlines()

        # ── Pass 1: strip noise, tag line types ───────────────────────────
        lines = []
        for line in raw_lines:
            s = line.rstrip()
            if not s:
                lines.append(("blank", ""))
            elif self._UL_RE.match(s):
                lines.append(("underline", ""))
            else:
                lines.append(("text", s))

        # ── Pass 2: classify each line ────────────────────────────────────
        # Each element: ("heading"|"step"|"plain"|"blank", depth, text, cmd)
        # Inline name:cmd splits are only applied inside numbered sections
        # (after the first _SEC_RE match) to avoid capturing subtitle / metadata.
        parsed = []
        _inside_numbered_section = False
        for kind, text in lines:
            if kind == "blank":
                parsed.append(("blank", 0, "", ""))
                continue

            if kind == "underline":
                # promote the previous plain line to a level-1 heading
                if parsed and parsed[-1][0] == "plain":
                    _, _, pt, _ = parsed.pop()
                    parsed.append(("heading", 1, pt, ""))
                continue

            stripped = text.strip()

            # ── numbered / lettered section heading ────────────────────────
            m = self._SEC_RE.match(stripped)
            if m:
                num   = m.group(1).rstrip(".")
                title = m.group(2).strip()
                depth = num.count(".") + 1
                _inside_numbered_section = True
                parsed.append(("heading", depth, title, ""))
                continue

            # ── ALL-CAPS line  ─────────────────────────────────────────────
            if self._CAPS_RE.match(stripped):
                parsed.append(("heading", 1, stripped.rstrip(":"), ""))
                continue

            # ── "Step N: ..."  ─────────────────────────────────────────────
            m = self._STEP_RE.match(text)
            if m:
                step_body = m.group(2).strip()
                name, cmd = self._split_name_cmd(step_body)
                if name:
                    tok_name = self._sanitize(name)
                    tok_cmd  = cmd
                else:
                    tok_name = "step_" + m.group(1)
                    tok_cmd  = step_body
                parsed.append(("step", 0, tok_name, tok_cmd))
                continue

            # ── bullet / arrow ─────────────────────────────────────────────
            m = self._BULLET_RE.match(text)
            if m:
                item = (m.group(1) or m.group(2)).strip()
                name, cmd = self._split_name_cmd(item)
                if name:
                    parsed.append(("step", 0, self._sanitize(name), cmd))
                else:
                    parsed.append(("step", 0, self._sanitize(item), item))
                continue

            # ── inline "name: command" on a plain text line ────────────────
            # Only apply inside numbered sections (after the first _SEC_RE match)
            # to avoid capturing subtitle / metadata / preamble lines.
            if _inside_numbered_section:
                name, cmd = self._split_name_cmd(stripped)
                if name and cmd != stripped:
                    parsed.append(("step", 0, self._sanitize(name), cmd))
                    continue
            parsed.append(("plain", 0, stripped, ""))

        # ── Pass 3: build hierarchy ────────────────────────────────────────
        h1_children = OrderedDict()   # h1_name → [h2_names or token_names]
        h2_children = OrderedDict()   # h2_name → [token_names]
        current_h1  = None
        current_h2  = None
        first_heading_seen = False

        for kind, depth, text, cmd in parsed:
            if kind in ("blank", "plain"):
                continue

            if kind == "heading":
                name = self._sanitize(text)
                if not name:
                    continue
                # First heading before any numbered section → grammar title, not a rule
                if not first_heading_seen and not self._name_explicit and depth <= 1:
                    # Use as grammar name only if no numbered sections have been registered yet
                    if not h1_children:
                        self.grammar_name = name
                        first_heading_seen = True
                        continue
                first_heading_seen = True
                if depth <= 1:
                    current_h1 = name
                    current_h2 = None
                    h1_children.setdefault(name, [])
                else:
                    current_h2 = name
                    h2_children.setdefault(name, [])
                    if current_h1 and name not in h1_children.get(current_h1, []):
                        h1_children.setdefault(current_h1, []).append(name)
                continue

            if kind == "step":
                tok_name = text  # already sanitized in pass 2
                tok_cmd  = cmd.strip()
                if not tok_name:
                    continue
                if tok_name not in self._tokens or (tok_cmd and not self._tokens[tok_name]):
                    self._tokens[tok_name] = tok_cmd
                parent = current_h2 or current_h1
                if parent:
                    bucket = h2_children if current_h2 else h1_children
                    if tok_name not in bucket.get(parent, []):
                        bucket.setdefault(parent, []).append(tok_name)

        # ── Pass 4: assemble rules ─────────────────────────────────────────
        if h1_children:
            self._rules[self.grammar_name] = list(h1_children.keys())
            for h1k, children in h1_children.items():
                if children:
                    self._rules[h1k] = children
                    for c in children:
                        if c in h2_children and h2_children[c]:
                            self._rules[c] = h2_children[c]
        elif self._tokens:
            self._rules[self.grammar_name] = list(self._tokens.keys())


# ─────────────────────────────────────────────────────────────────────────────
# PDF  (.pdf  — requires: pip install pypdf)
# ─────────────────────────────────────────────────────────────────────────────

class PDFGrammarConverter(BaseGrammarConverter):
    """Convert a PDF file to grammar + vocabulary files.

    Text is extracted with pypdf, then heading/list structure is inferred
    using heuristic rules (no font-size metadata needed):

        Short ALL-CAPS line (≤ 60 chars)  →  H1 or H2 heading
        Line ending with ':'               →  section label (H2/H3)
        Numbered line  '1. ...'            →  H3 / token group
        Bullet line  '• ...' / '- ...'    →  token

    Requires: pip install pypdf
    """

    def parse(self):
        try:
            import pypdf
        except ImportError:
            raise ImportError(
                "pypdf is required for PDF conversion.\n"
                "Install with:  pip install pypdf"
            )

        reader = pypdf.PdfReader(self.source)
        raw_lines = []
        for page in reader.pages:
            text = page.extract_text() or ""
            raw_lines.extend(text.splitlines())

        self._parse_lines(raw_lines)

    def _parse_lines(self, raw_lines):
        """Heuristic heading/token detection from plain text lines."""
        h2_children = OrderedDict()   # h2_name → [children]
        current_h2  = None
        current_h3  = None

        def is_heading(line):
            s = line.strip()
            return s and len(s) <= 60 and s == s.upper() and re.search(r'[A-Z]', s)

        def is_section_label(line):
            return line.strip().endswith(':') and len(line.strip()) <= 80

        def is_numbered(line):
            return bool(re.match(r'^\s*\d+[\.\)]\s+', line))

        def is_bullet(line):
            return bool(re.match(r'^\s*[•\-\*]\s+', line))

        for line in raw_lines:
            s = line.strip()
            if not s:
                continue

            if is_heading(s):
                if not self._name_explicit and not current_h2:
                    self.grammar_name = self._sanitize(s)
                else:
                    current_h2  = s
                    current_h3  = None
                    h2k         = self._sanitize(s)
                    h2_children.setdefault(h2k, [])
                continue

            if is_section_label(s):
                label = s.rstrip(':').strip()
                if current_h2 is None:
                    if not self._name_explicit:
                        self.grammar_name = self._sanitize(label)
                else:
                    current_h3  = label
                    h3k         = self._sanitize(label)
                    h2k         = self._sanitize(current_h2)
                    if h3k not in h2_children.get(h2k, []):
                        h2_children.setdefault(h2k, []).append(h3k)
                continue

            if is_numbered(s):
                tok = self._sanitize(re.sub(r'^\d+[\.\)]\s+', '', s))
                self._tokens.setdefault(tok, "")
                parent = self._sanitize(current_h3 or current_h2 or self.grammar_name)
                h2_children.setdefault(parent, [])
                if tok not in h2_children[parent]:
                    h2_children[parent].append(tok)
                continue

            if is_bullet(s):
                item = re.sub(r'^[•\-\*]\s+', '', s)
                if ':' in item:
                    tok_label, _, cmd = item.partition(':')
                    tok = self._sanitize(tok_label)
                    self._tokens[tok] = cmd.strip()
                else:
                    tok = self._sanitize(item)
                    self._tokens.setdefault(tok, "")
                parent = self._sanitize(current_h3 or current_h2 or self.grammar_name)
                h2_children.setdefault(parent, [])
                if tok not in h2_children[parent]:
                    h2_children[parent].append(tok)

        # Build rules
        if h2_children:
            top = [k for k in h2_children if k != self.grammar_name]
            self._rules[self.grammar_name] = top
            for h2k, children in h2_children.items():
                if h2k == self.grammar_name:
                    continue
                if children:
                    self._rules[h2k] = children
                    for c in children:
                        self._tokens.setdefault(c, "")
        elif self._tokens:
            self._rules[self.grammar_name] = list(self._tokens.keys())


# ─────────────────────────────────────────────────────────────────────────────
# Web page  (http / https URL — stdlib only: urllib + html.parser)
# ─────────────────────────────────────────────────────────────────────────────

class WebGrammarConverter(BaseGrammarConverter):
    """Convert a web page to grammar + vocabulary files.

    Fetches the page with urllib.request (no third-party deps).
    Parses HTML structure with stdlib html.parser.

    Document structure mapping:
        <h1>   →  grammar name (unless overridden)
        <h2>   →  top-level rule group
        <h3>   →  sub-rule or token group
        <li>   →  token (text content used as name; <code> inside = command)
        <code> / <pre>  →  command value for the current token/heading

    Uses a 10-second timeout for the HTTP request.
    """

    def parse(self):
        import urllib.request
        from html.parser import HTMLParser

        req = urllib.request.Request(
            self.source,
            headers={"User-Agent": "model-tools-grammar/1.0"},
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            charset = "utf-8"
            ct = resp.headers.get("Content-Type", "")
            if "charset=" in ct:
                charset = ct.split("charset=")[-1].split(";")[0].strip()
            html = resp.read().decode(charset, errors="replace")

        parser = _HTMLStructureParser()
        parser.feed(html)
        self._build_from_html(parser)

    def _build_from_html(self, parser):
        """Translate the HTML structure collected by _HTMLStructureParser into rules."""
        h2_children = OrderedDict()
        current_h2  = None
        current_h3  = None

        for kind, text, code in parser.items:
            text = text.strip()
            code = (code or "").strip()
            if not text:
                continue

            if kind == "h1":
                if not self._name_explicit:
                    self.grammar_name = self._sanitize(text)

            elif kind == "h2":
                current_h2  = text
                current_h3  = None
                h2k         = self._sanitize(text)
                h2_children.setdefault(h2k, [])

            elif kind == "h3":
                current_h3  = text
                h3k         = self._sanitize(text)
                if current_h2:
                    h2k = self._sanitize(current_h2)
                    if h3k not in h2_children.get(h2k, []):
                        h2_children.setdefault(h2k, []).append(h3k)

            elif kind == "li":
                # Parse "name: command" or just "name"
                if ':' in text:
                    tok_label, _, cmd = text.partition(':')
                    tok = self._sanitize(tok_label)
                    self._tokens[tok] = (code or cmd).strip()
                else:
                    tok = self._sanitize(text)
                    self._tokens[tok] = code
                parent = (self._sanitize(current_h3) if current_h3 else
                          self._sanitize(current_h2) if current_h2 else None)
                if parent:
                    h2_children.setdefault(parent, [])
                    if tok not in h2_children[parent]:
                        h2_children[parent].append(tok)

        # Build rules
        if h2_children:
            top = [k for k in h2_children if k != self.grammar_name]
            self._rules[self.grammar_name] = top
            for h2k, children in h2_children.items():
                if h2k == self.grammar_name:
                    continue
                if children:
                    self._rules[h2k] = children
                    for c in children:
                        self._tokens.setdefault(c, "")
        elif self._tokens:
            self._rules[self.grammar_name] = list(self._tokens.keys())


class _HTMLStructureParser:
    """Minimal HTML parser that collects heading/list structure.

    Produces self.items: list of (kind, text, code) tuples where
    kind ∈ {'h1','h2','h3','li'}.
    """

    from html.parser import HTMLParser as _HP

    class _Inner(_HP):
        def __init__(self):
            super().__init__()
            self.items     = []
            self._cur_tag  = None
            self._buf      = []
            self._code_buf = []
            self._in_code  = False
            self._skip_tags = {"script", "style", "nav", "footer", "head"}
            self._skip_depth = 0

        def handle_starttag(self, tag, attrs):
            if tag in self._skip_tags:
                self._skip_depth += 1
                return
            if self._skip_depth:
                return
            if tag in ("h1", "h2", "h3", "li"):
                self._cur_tag  = tag
                self._buf      = []
                self._code_buf = []
                self._in_code  = False
            elif tag in ("code", "pre") and self._cur_tag:
                self._in_code = True

        def handle_endtag(self, tag):
            if tag in self._skip_tags:
                self._skip_depth = max(0, self._skip_depth - 1)
                return
            if self._skip_depth:
                return
            if tag in ("code", "pre"):
                self._in_code = False
            if tag == self._cur_tag:
                text = re.sub(r'\s+', ' ', "".join(self._buf)).strip()
                code = re.sub(r'\s+', ' ', "".join(self._code_buf)).strip()
                if text:
                    self.items.append((self._cur_tag, text, code))
                self._cur_tag = None

        def handle_data(self, data):
            if self._skip_depth or self._cur_tag is None:
                return
            if self._in_code:
                self._code_buf.append(data)
            else:
                self._buf.append(data)

    def __init__(self):
        self._parser = self._Inner()

    def feed(self, html):
        self._parser.feed(html)

    @property
    def items(self):
        return self._parser.items


# ─────────────────────────────────────────────────────────────────────────────
# Model-assisted  (any Ollama model interprets the source)
# ─────────────────────────────────────────────────────────────────────────────

class ModelAssistedGrammarConverter(BaseGrammarConverter):
    """Use an Ollama model to extract grammar + vocabulary from any source.

    Works with all source formats: Mermaid, Markdown, PDF, web pages, and
    plain text.  The model interprets the raw content and returns structured
    JSON that is parsed directly into _rules and _tokens.

    This is the recommended path when the source is a dense technical manual,
    a web page with inconsistent HTML structure, or any document where the
    heuristic converters would miss domain-specific command syntax.

    Args:
        source      : file path or URL
        grammar_name: override the derived grammar name (optional)
        exec_mode   : "shell" or "python" (default: "shell")
        model_name  : Ollama model to use (e.g. "qwen2:7b", "llama3")
        ollama_host : Ollama API base URL (default: http://127.0.0.1:11434)
        max_chars   : maximum source characters sent to the model (default: 6000)

    Expected model response format (JSON, no markdown wrapping):
        {
          "_grammar": "procedure_name",
          "_exec": "shell",
          "__rules__": {
            "procedure_name": ["group1", "group2"],
            "group1": ["token1", "token2"]
          },
          "token1": "command or empty string",
          "token2": "command or empty string"
        }
    """

    _EXTRACTION_PROMPT = (
        "You are a technical grammar extraction assistant.\n"
        "Analyse the following technical document and extract a structured procedure grammar.\n\n"
        "Return ONLY a valid JSON object — no markdown, no explanation — with this exact structure:\n"
        "{\n"
        '  "_grammar": "snake_case_procedure_name",\n'
        '  "_exec": "shell",\n'
        '  "__rules__": {\n'
        '    "procedure_name": ["group_a", "group_b"],\n'
        '    "group_a": ["token_1", "token_2"]\n'
        "  },\n"
        '  "token_1": "actual shell command or empty string",\n'
        '  "token_2": "actual shell command or empty string"\n'
        "}\n\n"
        "Requirements:\n"
        "- All names must be snake_case\n"
        "- __rules__ maps each non-terminal rule to its ordered list of children\n"
        "- Every child that is NOT itself a key in __rules__ must appear as a top-level token key\n"
        "- Token values should be the real command if visible in the source, otherwise \"\"\n"
        "- _exec is 'python' if token values are Python code, otherwise 'shell'\n\n"
        "Document:\n"
    )

    def __init__(self, source, grammar_name=None, exec_mode="shell",
                 model_name="qwen2:7b", ollama_host="http://127.0.0.1:11434",
                 max_chars=6000):
        super().__init__(source, grammar_name, exec_mode)
        self.model_name  = model_name
        self.ollama_host = ollama_host.rstrip("/")
        self.max_chars   = max_chars

    # ── text extraction helpers ─────────────────────────────────────────────

    def _extract_text(self):
        """Extract plain text from the source, routing by format."""
        src = str(self.source)
        if src.startswith("http://") or src.startswith("https://"):
            return self._fetch_web_text(src)
        ext = os.path.splitext(src)[1].lower()
        if ext == ".pdf":
            return self._extract_pdf_text(src)
        with open(src, "r", encoding="utf-8", errors="replace") as fh:
            return fh.read()

    @staticmethod
    def _fetch_web_text(url):
        import urllib.request
        from html.parser import HTMLParser as _HP

        class _TE(_HP):
            def __init__(self):
                super().__init__()
                self._buf   = []
                self._skip  = {"script", "style", "nav", "footer", "head"}
                self._depth = 0
            def handle_starttag(self, tag, attrs):
                if tag in self._skip:
                    self._depth += 1
            def handle_endtag(self, tag):
                if tag in self._skip:
                    self._depth = max(0, self._depth - 1)
            def handle_data(self, data):
                if not self._depth:
                    self._buf.append(data)

        req = urllib.request.Request(url, headers={"User-Agent": "model-tools-grammar/1.0"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            charset = "utf-8"
            ct = resp.headers.get("Content-Type", "")
            if "charset=" in ct:
                charset = ct.split("charset=")[-1].split(";")[0].strip()
            html = resp.read().decode(charset, errors="replace")
        p = _TE()
        p.feed(html)
        return re.sub(r'\n{3,}', '\n\n', "".join(p._buf))

    @staticmethod
    def _extract_pdf_text(path):
        try:
            import pypdf
        except ImportError:
            raise ImportError("pip install pypdf")
        reader = pypdf.PdfReader(path)
        return "\n".join(page.extract_text() or "" for page in reader.pages)

    # ── model query ─────────────────────────────────────────────────────────

    def _query_model(self, text):
        """Send text to the Ollama model and return the raw response string."""
        import urllib.request as _ur, json as _j

        if len(text) > self.max_chars:
            text = text[:self.max_chars] + "\n...[truncated]"

        payload = _j.dumps({
            "model":  self.model_name,
            "prompt": self._EXTRACTION_PROMPT + text,
            "stream": False,
        }).encode("utf-8")

        req = _ur.Request(
            self.ollama_host + "/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
        )
        with _ur.urlopen(req, timeout=180) as resp:
            data = _j.loads(resp.read())
        return data.get("response", "")

    # ── response parsing ────────────────────────────────────────────────────

    def _parse_response(self, response):
        """Parse the model's JSON response into _rules and _tokens."""
        import json as _j

        # Model may wrap the JSON in a markdown code fence — strip it
        text = re.sub(r'^```[a-z]*\n?', '', response.strip(), flags=re.M)
        text = re.sub(r'\n?```$', '', text.strip(), flags=re.M)

        # Find the outermost JSON object
        m = re.search(r'\{.*\}', text, re.DOTALL)
        if not m:
            raise ValueError(
                "Model did not return valid JSON.\nResponse preview: " + response[:300]
            )
        data = _j.loads(m.group(0))

        # Grammar name
        if not self._name_explicit and "_grammar" in data:
            self.grammar_name = self._sanitize(data["_grammar"])

        # Exec mode
        if "_exec" in data:
            self.exec_mode = data["_exec"]

        # Rules structure  (__rules__ key)
        for rule_raw, children_raw in data.get("__rules__", {}).items():
            rule = self._sanitize(rule_raw)
            self._rules[rule] = [self._sanitize(c) for c in (children_raw or [])]

        # Token commands  (any top-level key that is not _prefixed or __rules__)
        for key, value in data.items():
            if key.startswith("_"):
                continue
            tok = self._sanitize(key)
            self._tokens[tok] = str(value) if value else ""

        # Fallback: flat structure when the model returned tokens but no rules
        if not self._rules and self._tokens:
            self._rules[self.grammar_name] = list(self._tokens.keys())

    # ── main entry point ────────────────────────────────────────────────────

    def parse(self):
        raw_text  = self._extract_text()
        response  = self._query_model(raw_text)
        self._parse_response(response)
