#!/usr/bin/env python3
"""Export tokenizer support for the device npu_query: a per-token decode table
(token id -> display string, BPE space marker resolved) + the rule-name prompts
+ the EOS id. Lets the device tokenize the fixed rule prompts and detokenize the
NPU's autoregressive output without a full BPE tokenizer on-chip."""
import os, sys, json
from transformers import AutoTokenizer

MODEL_DIR = "models/generated/convolutional/model_calculator_tcn_version_1"
OUT_C = "STM32N6/AI_TO_NPU_1/run-23/FSBL/AI/network_tokens.c"
OUT_H = "STM32N6/AI_TO_NPU_1/run-23/FSBL/AI/network_tokens.h"
RULES = ["expr", "term", "factor", "number", "digit"]

tok = AutoTokenizer.from_pretrained(MODEL_DIR)
V = tok.vocab_size
eos = tok.eos_token_id

def cstr(s):
    out = []
    for ch in s:
        if ch == '\\': out.append('\\\\')
        elif ch == '"': out.append('\\"')
        elif ch == '\n': out.append('\\n')
        elif ch == '\r': out.append('\\r')
        elif ch == '\t': out.append('\\t')
        elif 32 <= ord(ch) < 127: out.append(ch)
        else: out.append('\\x%02x' % (ord(ch) & 0xff))
    return '"' + ''.join(out) + '"'

# per-token display string: decode each id alone (handles the Ġ space marker)
decode = [tok.decode([i]) for i in range(V)]
prompts = {r: tok(r, add_special_tokens=False)["input_ids"] for r in RULES}

with open(OUT_H, "w") as f:
    f.write("#ifndef NETWORK_TOKENS_H\n#define NETWORK_TOKENS_H\n#include <stdint.h>\n\n")
    f.write(f"#define TOK_VOCAB   {V}\n#define TOK_EOS_ID  {eos}\n")
    f.write(f"#define TOK_NUM_RULES {len(RULES)}\n#define TOK_MAX_PROMPT {max(len(v) for v in prompts.values())}\n\n")
    f.write("extern const char* const g_tok_decode[TOK_VOCAB];      /* id -> display string */\n")
    f.write("extern const char* const g_rule_names[TOK_NUM_RULES];  /* rule name strings */\n")
    f.write("extern const int16_t     g_rule_prompt[TOK_NUM_RULES][TOK_MAX_PROMPT]; /* token ids, -1 pad */\n")
    f.write("extern const uint8_t     g_rule_prompt_len[TOK_NUM_RULES];\n\n#endif\n")

mp = max(len(v) for v in prompts.values())
with open(OUT_C, "w") as f:
    f.write('/* Generated by export_tokens.py — device tokenizer support. */\n')
    f.write('#include "network_tokens.h"\n\n')
    f.write("const char* const g_tok_decode[TOK_VOCAB] = {\n")
    for i in range(V):
        f.write("  " + cstr(decode[i]) + ",\n")
    f.write("};\n\n")
    f.write("const char* const g_rule_names[TOK_NUM_RULES] = { " +
            ", ".join(cstr(r) for r in RULES) + " };\n\n")
    f.write("const int16_t g_rule_prompt[TOK_NUM_RULES][TOK_MAX_PROMPT] = {\n")
    for r in RULES:
        ids = prompts[r] + [-1] * (mp - len(prompts[r]))
        f.write("  { " + ", ".join(str(x) for x in ids) + " },\n")
    f.write("};\n\n")
    f.write("const uint8_t g_rule_prompt_len[TOK_NUM_RULES] = { " +
            ", ".join(str(len(prompts[r])) for r in RULES) + " };\n")

print(f"vocab={V} eos={eos}")
for r in RULES:
    print(f"  prompt {r!r} -> ids {prompts[r]}  decode-check: {''.join(decode[i] for i in prompts[r])!r}")
print(f"exported -> {OUT_C} ({os.path.getsize(OUT_C)} bytes)")
