#!/usr/bin/env python3
"""Export the TCN model's CPU embedding table (nn.Embedding[vocab,dim]) as an int8
C array for the device npu_query. The NPU body takes int8 embeddings (S8, scale/zp
from the model header), so we pre-quantize the embedding with that same scale/zp;
the device Gather then just copies int8 rows into the NPU input tensor."""
import sys, os, torch
sys.path.insert(0, "scripts/model_generation")
from model_create_npu_tcn import GrammarTCN

MODEL_DIR = "models/generated/convolutional/model_calculator_tcn_version_1"
OUT_C = "STM32N6/AI_TO_NPU_1/run-23/FSBL/AI/network_embed.c"
OUT_H = "STM32N6/AI_TO_NPU_1/run-23/FSBL/AI/network_embed.h"
VOCAB, EMBED = 374, 256
SCALE, ZP = 0.029472799971699715, -4          # STAI_NETWORK_IN_1_SCALE / ZERO_POINT

model = GrammarTCN(VOCAB, EMBED)
model.load_state_dict(torch.load(os.path.join(MODEL_DIR, "model_calculator_tcn_version_1.pt"),
                                 map_location="cpu"))
emb = model.embed.weight.detach()                       # [VOCAB, EMBED] fp32
q = torch.clamp(torch.round(emb / SCALE) + ZP, -128, 127).to(torch.int8)
flat = q.flatten().tolist()                             # row-major [token][channel]

with open(OUT_H, "w") as f:
    f.write("#ifndef NETWORK_EMBED_H\n#define NETWORK_EMBED_H\n#include <stdint.h>\n\n")
    f.write("/* int8 token embedding table [vocab][dim] = g_embed_table[token*EMBED_DIM + ch].\n")
    f.write(f" * Pre-quantized with the NPU input scale={SCALE} zero_point={ZP}. */\n")
    f.write(f"#define EMBED_VOCAB {VOCAB}\n#define EMBED_DIM   {EMBED}\n\n")
    f.write(f"extern const int8_t g_embed_table[{VOCAB} * {EMBED}];\n\n#endif /* NETWORK_EMBED_H */\n")

with open(OUT_C, "w") as f:
    f.write('/* Generated by export_embed.py — int8 CPU embedding table for npu_query. */\n')
    f.write('#include "network_embed.h"\n\n')
    f.write(f"const int8_t g_embed_table[{VOCAB} * {EMBED}] = {{\n")
    for i in range(0, len(flat), 20):
        f.write("  " + ",".join("%d" % v for v in flat[i:i+20]) + ",\n")
    f.write("};\n")

print(f"exported {VOCAB}x{EMBED} int8 embedding -> {OUT_C}")
print(f"  C size: {os.path.getsize(OUT_C)} bytes ; table: {VOCAB*EMBED} int8 = {VOCAB*EMBED//1024} KB")
print(f"  q range: [{int(q.min())}, {int(q.max())}]  (sanity: should span much of [-128,127])")
